---
- name: "Installation packages "
  package:
    name: "{{ package_install }}"
    state: present
  become: yes
  when: package_install is defined 
  tags:
    - package_install

- name: "Delete packages"
  package:
    name: "{{ package_uninstall }}"
    state: present
  become: yes
  when: package_uninstall is defined 
  tags:
    - package_uninstall
